// AUTOMATICALLY GENERATED BY ANDES SDK. MODIFYING NOT RECOMMENDED.

#pragma once

#include <andes_res_types.h>


// ---- audio ----
extern AudioResource RES_music_main;
extern AudioResource RES_sfx_select;
extern AudioResource RES_sfx_enter;

// ---- palettes ----
extern PaletteResource RES_palette_main;

// ---- rawdata ----

// ---- spritesets ----
extern const SpriteSetFrame FRAMES_spriteset_smallframe[];
extern SpriteSetResource RES_spriteset_smallframe;
extern const SpriteSetFrame FRAMES_spriteset_chevron[];
extern SpriteSetResource RES_spriteset_chevron;

// ---- tilesets ----
extern TileSetResource RES_tileset_font;
extern TileSetResource RES_tileset_bg;
extern TileSetResource RES_tileset_bigframe;
extern TileSetResource RES_tileset_cursor;

// ---- tilemaps ----
