// AUTOMATICALLY GENERATED BY ANDES SDK. MODIFYING NOT RECOMMENDED.

#include <andes_resources.h>


// ---- audio ----
AudioResource RES_music_main = { .address = 21196, .size = 2860200, .loopStart = 652580 };
AudioResource RES_sfx_select = { .address = 2881396, .size = 2612, .loopStart = -1 };
AudioResource RES_sfx_enter = { .address = 2884008, .size = 25799, .loopStart = -1 };

// ---- palettes ----
const unsigned char DATA_palette_main[][3] = { { 0x8, 0x6, 0x6 }, { 0x37, 0x38, 0x3a }, { 0x28, 0x29, 0x30 }, { 0x1a, 0x1b, 0x26 }, { 0x10, 0x12, 0x1c }, { 0xa, 0xa, 0x11 }, { 0x5, 0x6, 0xb }, { 0x2a, 0x14, 0xc }, { 0x33, 0x1d, 0xa }, { 0x3c, 0x2d, 0x10 }, { 0x3f, 0x3b, 0x20 }, { 0xe, 0x1f, 0x13 }, { 0xb, 0x15, 0x14 }, { 0xa, 0xd, 0x10 }, { 0xe, 0xf, 0x17 }, { 0x13, 0x1a, 0x21 },  };
PaletteResource RES_palette_main = { .data = DATA_palette_main, .size = 48 };

// ---- rawdata ----

// ---- spritesets ----
const SpriteSetFrame FRAMES_spriteset_smallframe[] = {
  { .offset = 0, .width = 64, .height = 52 },
};
SpriteSetResource RES_spriteset_smallframe = { .address = 2909807, .size = 3190, .frames = FRAMES_spriteset_smallframe };

const SpriteSetFrame FRAMES_spriteset_chevron[] = {
  { .offset = 0, .width = 24, .height = 48 },
  { .offset = 352, .width = 48, .height = 24 },
  { .offset = 816, .width = 48, .height = 24 },
};
SpriteSetResource RES_spriteset_chevron = { .address = 2912997, .size = 1280, .frames = FRAMES_spriteset_chevron };


// ---- tilesets ----
TileSetResource RES_tileset_font = { .address = 2914277, .size = 8192, .planeArrangement = NULL };
uint16_t ARRANGE_tileset_bg[] = { 1, 2, 3, 4, 5, 6, 7, 8, 3, 4, 1, 2, 7, 8, 5, 6,  };
TileSetResource RES_tileset_bg = { .address = 2922469, .size = 512, .planeArrangement = ARRANGE_tileset_bg };
uint16_t ARRANGE_tileset_bigframe[] = { 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40,  };
TileSetResource RES_tileset_bigframe = { .address = 2922981, .size = 576, .planeArrangement = ARRANGE_tileset_bigframe };
uint16_t ARRANGE_tileset_cursor[] = { 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 65, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 68, 69, 70, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 71, 72, 73, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 66, 74, 74, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 75, 76, 77, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 67, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 79,  };
TileSetResource RES_tileset_cursor = { .address = 2923557, .size = 1024, .planeArrangement = ARRANGE_tileset_cursor };

// ---- tilemaps ----
