#define BIG_THUMBNAIL_WIDTH 256
#define BIG_THUMBNAIL_HEIGHT 192
#define SMALL_THUMBNAIL_WIDTH 64
#define SMALL_THUMBNAIL_HEIGHT 48

#define ANDES_HEADER_SIZE 13
#define STRING_BUF_SIZE 1024

#define TILESET_BG_OFFSET 1
#define TILESET_BIGFRAME_OFFSET 32
#define TILESET_FONT_OFFSET 8063