#define BIG_THUMBNAIL_WIDTH 160
#define BIG_THUMBNAIL_HEIGHT 120
#define BIG_THUMBNAIL_COLOURS 120

#define SMALL_THUMBNAIL_WIDTH 48
#define SMALL_THUMBNAIL_HEIGHT 36
#define SMALL_THUMBNAIL_COLOURS 24

#define THUMBNAIL_PALETTE_OFFSET 16

#define ANDES_HEADER_SIZE 13
#define STRING_BUF_SIZE 1024
#define MAX_APP_COUNT 4096
#define APP_ENTRY_AMOUNT 5

#define BG_MOVEMENT_RADIUS_X 40
#define BG_MOVEMENT_RADIUS_Y 40
#define BG_MOVEMENT_SPEED 0.01

#define ENTRY_CIRCLE_RADIUS 180
#define ENTRY_CIRCLE_OFFSET 30

#define TILESET_BG_OFFSET 1
#define TILESET_BIGFRAME_OFFSET 32
#define TILESET_CURSOR_OFFSET 64
#define TILESET_FONT_OFFSET 8063

#define MATH_PI 3.1416